line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "I", "B", "UP", "SIM", "N", "RUF"]
ignore = ["E501"]
mccabe.max-complexity = 10

[lint.per-file-ignores]
"tests/*" = ["S101", "N802"]
"chapters/*" = ["N803", "N806"]
